# Generated by Django 5.0.6 on 2024-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_delete_someinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to='images', verbose_name='Profile Picture'),
        ),
    ]
