# Generated by Django 5.0.6 on 2024-06-04 21:04

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_groupchat_userslist_alter_account_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='JoinRequest',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
