# Generated by Django 5.0.6 on 2024-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_account_about_groupchat_joinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(db_index=True)),
                ('RoomName', models.CharField(db_index=True)),
                ('UserDetails', models.JSONField()),
                ('status', models.CharField(default='False')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='JoinRequest',
        ),
    ]
