# Generated by Django 5.0.6 on 2024-06-05 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_requesttable_remove_groupchat_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='Creator',
            field=models.EmailField(default='kenjicladia@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='Creator',
            field=models.EmailField(db_index=True, default='kenjicladia@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
    ]
