# Generated by Django 5.0.6 on 2024-06-07 13:16

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0012_alter_groupchat_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalchats',
            name='about',
        ),
        migrations.RemoveField(
            model_name='personalchats',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personalchats',
            name='title',
        ),
        migrations.AddField(
            model_name='personalchats',
            name='Details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalchats',
            name='RecieverId',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
        migrations.AddField(
            model_name='personalchats',
            name='SenderId',
            field=models.CharField(max_length=50, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
        migrations.AlterField(
            model_name='communitychat',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='personalchats',
            name='ChatLog',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalchats',
            name='DateCreated',
            field=models.CharField(blank=True, null=True, verbose_name='Date Created'),
        ),
    ]
