# Generated by Django 5.0.6 on 2024-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0016_alter_notepad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='LastText',
            field=models.JSONField(blank=True, default='last text', null=True),
        ),
    ]
