# Generated by Django 5.0.6 on 2024-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0017_alter_notepad_lasttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='LastText',
            field=models.TextField(blank=True, default='last text', null=True),
        ),
    ]
