# Generated by Django 5.0.6 on 2024-06-23 18:37

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0018_alter_notepad_lasttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About'),
        ),
    ]
