# Generated by Django 5.0.6 on 2024-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0019_alter_account_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('OpenedDate', models.CharField(blank=True, max_length=500, null=True)),
                ('Details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='JobsHistory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='rattings',
            field=models.IntegerField(default=1),
        ),
    ]
