# Generated by Django 5.0.6 on 2024-07-08 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0020_jobstable_account_jobshistory_account_rattings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='requestedJobs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstable',
            name='Request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstable',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
