# Generated by Django 5.0.6 on 2024-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0021_account_requestedjobs_jobstable_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstable',
            name='RequestIDs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
