# Generated by Django 5.0.6 on 2024-09-19 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0023_onlinestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestJobTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.JSONField(blank=True, null=True)),
                ('userID', models.CharField(blank=True, db_index=True, null=True)),
                ('JobID', models.CharField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.AddField(
            model_name='jobstable',
            name='AcceptedIDs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstable',
            name='AcceptedRequest',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstable',
            name='CreatorsID',
            field=models.CharField(blank=True, null=True),
        ),
    ]
