# Generated by Django 5.0.6 on 2024-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0024_requestjobtable_jobstable_acceptedids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='groupname',
            field=models.CharField(blank=True, null=True),
        ),
    ]
