# Generated by Django 5.0.6 on 2024-06-01 16:38

import Chat.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField(auto_created=True, verbose_name='Date Created')),
                ('group_name', models.CharField(db_index=True, max_length=50, unique=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Group Id')),
                ('title', models.CharField(max_length=50, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Name')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Profile Picture')),
                ('about', models.CharField(blank=True, max_length=30, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About')),
                ('ChatLogs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField(auto_created=True, verbose_name='Date Created')),
                ('group_name', models.CharField(db_index=True, max_length=50, unique=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Group Id')),
                ('title', models.CharField(max_length=50, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Name')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('about', models.CharField(blank=True, max_length=30, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About')),
                ('ChatLog', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=40, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=30, validators=[Chat.models.alphanumeric_validator])),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='useraccount_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='useraccount_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistableToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
    ]
