# Generated by Django 5.0.6 on 2024-06-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='ChatLogs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
