# Generated by Django 5.0.6 on 2024-06-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_groupchat_chatlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeInfo',
        ),
    ]
