# Generated by Django 5.0.6 on 2024-06-04 14:42

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_groupchat_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField(auto_created=True, verbose_name='Date Created')),
                ('group_name', models.CharField(db_index=True, max_length=50, unique=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Group Id')),
                ('title', models.CharField(max_length=50, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Name')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('ProfilePic', models.ImageField(blank=True, default='fallback.jpeg', upload_to='images/', verbose_name='Profile Picture')),
                ('about', models.CharField(blank=True, max_length=30, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='About')),
                ('ChatLogs', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to='images/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='fallback.jpeg', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
