# Generated by Django 5.0.6 on 2024-06-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_communitychat_account_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='UsersList',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='images/fallback.jpeg', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
