# Generated by Django 5.0.6 on 2024-06-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_groupchat_creator_requesttable_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='date_field',
            field=models.DateField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='DateCreated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
