# Generated by Django 5.0.6 on 2024-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_groupchat_date_field_alter_groupchat_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='date_field',
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='DateCreated',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Date Created'),
        ),
    ]
