# Generated by Django 5.0.6 on 2024-06-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_remove_groupchat_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='Creator',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
