# Generated by Django 5.0.6 on 2024-06-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0013_remove_personalchats_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='DateCreated',
            field=models.CharField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='DateCreated',
            field=models.CharField(blank=True, null=True, verbose_name='Date Created'),
        ),
    ]
