# Generated by Django 5.0.6 on 2024-06-15 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0014_alter_communitychat_datecreated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator])),
                ('DateCreated', models.CharField(blank=True, null=True)),
                ('LastText', models.JSONField(blank=True, null=True)),
                ('NoteLog', models.JSONField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
