# Generated by Django 5.0.6 on 2024-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0015_notepad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='title',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
