# Generated by Django 5.0.6 on 2024-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0022_jobstable_requestids'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.JSONField(blank=True, null=True)),
                ('lastSeen', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
