# Generated by Django 5.0.6 on 2024-10-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0025_requesttable_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ProfileAbout',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ProfilePhotos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ProfilePost',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ProfileRepository',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ProfileVideos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
