# Generated by Django 5.0.6 on 2024-10-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0026_account_profileabout_account_profilephotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ProfileCoverPhoto',
            field=models.ImageField(blank=True, default='images/fallback.jpeg', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
