# Generated by Django 5.0.6 on 2024-10-21 21:08

import Chat.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0027_account_profilecoverphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ProfilePost',
        ),
        migrations.AlterField(
            model_name='account',
            name='ProfileCoverPhoto',
            field=models.ImageField(blank=True, default='images/fallback.jpeg', upload_to='images/', verbose_name='Profile Cover photo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[Chat.models.alphanumeric_validator])),
                ('content', models.TextField()),
                ('datePosted', models.CharField(max_length=30)),
                ('totalShares', models.TextField()),
                ('postUserDetails', models.JSONField(blank=True, null=True)),
                ('postPrivacy', models.CharField(max_length=30, validators=[Chat.models.alphanumeric_validator])),
                ('likes', models.JSONField(blank=True, null=True)),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[Chat.models.alphanumeric_validator])),
                ('CommentUserDetails', models.JSONField(blank=True, null=True)),
                ('dateCommented', models.CharField(max_length=30)),
                ('replyCommentDetails', models.JSONField(blank=True, null=True)),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Chat.post')),
            ],
        ),
    ]
