# Generated by Django 5.0.6 on 2024-10-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0028_remove_account_profilepost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Chat.post'),
        ),
    ]
