# Generated by Django 5.0.6 on 2024-10-27 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0029_alter_postcomment_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedpost', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedpost', to='Chat.post')),
            ],
        ),
    ]
