# Generated by Django 5.0.6 on 2024-10-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0030_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='post_id',
            new_name='post',
        ),
    ]
