# Generated by Django 5.0.6 on 2024-10-30 20:32

import Chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0031_rename_post_id_savedpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postPrivacy',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='totalShares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='dateCommented',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='message',
            field=models.TextField(blank=True, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
        migrations.CreateModel(
            name='FolderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('dateCreated', models.CharField(blank=True, max_length=60, null=True)),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('dateCreated', models.CharField(blank=True, max_length=60, null=True)),
                ('size', models.CharField(blank=True, max_length=60, null=True)),
                ('fileUrl', models.TextField(blank=True, null=True, validators=[Chat.models.alphanumeric_validator])),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Chat.foldertable')),
            ],
        ),
    ]
