# Generated by Django 5.0.6 on 2024-11-01 09:22

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0032_alter_post_content_alter_post_postprivacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetable',
            name='type',
            field=models.TextField(blank=True, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
    ]
