# Generated by Django 5.0.6 on 2024-11-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0033_filetable_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('post', 'account_email')},
        ),
    ]
