# Generated by Django 5.0.6 on 2024-11-07 18:53

import Chat.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0034_alter_savedpost_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchats',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=40, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='personalchats',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[Chat.models.alphanumeric_validator]),
        ),
    ]
