# Generated by Django 5.0.6 on 2024-11-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0035_personalchats_email_personalchats_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='account_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestTable', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='dateRequested',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
