# Generated by Django 5.0.6 on 2024-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0036_requesttable_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychat',
            name='Creator',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
