# Generated by Django 5.0.6 on 2024-11-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0037_communitychat_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='Creator',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='Creator',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
