# Generated by Django 5.0.6 on 2024-11-10 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0038_alter_communitychat_creator_alter_groupchat_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobsTable',
        ),
        migrations.DeleteModel(
            name='RequestJobTable',
        ),
        migrations.AddField(
            model_name='communitychat',
            name='account_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='account_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Groups', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='notepad',
            name='account_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notepad', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
