# Generated by Django 5.0.6 on 2024-11-10 16:58

import Chat.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0039_delete_jobstable_delete_requestjobtable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='UsersList',
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='group_name',
            field=models.CharField(db_index=True, default=Chat.models.generate_unique_id, max_length=5000, unique=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Group Id'),
        ),
        migrations.CreateModel(
            name='GroupChatUsersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[Chat.models.alphanumeric_validator])),
                ('email', models.EmailField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('group_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersList', to='Chat.groupchat')),
            ],
        ),
    ]
