# Generated by Django 5.0.6 on 2024-11-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0040_remove_groupchat_userslist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatuserslist',
            name='group_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersList', to='Chat.groupchat', to_field='group_name'),
        ),
    ]
