# Generated by Django 5.0.6 on 2024-11-10 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0041_alter_groupchatuserslist_group_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatuserslist',
            name='email',
            field=models.EmailField(db_index=True, max_length=40, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
