# Generated by Django 5.0.6 on 2024-11-10 18:22

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0042_alter_groupchatuserslist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='title',
            field=models.CharField(db_index=True, max_length=50, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Name'),
        ),
    ]
