# Generated by Django 5.0.6 on 2024-11-13 14:55

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0043_alter_groupchat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='group_name',
            field=models.CharField(db_index=True, default=Chat.models.generate_unique_id, max_length=5000, unique=True, validators=[Chat.models.alphanumeric_validator], verbose_name='community Id'),
        ),
        migrations.AlterField(
            model_name='communitychat',
            name='title',
            field=models.CharField(db_index=True, max_length=50, null=True, validators=[Chat.models.alphanumeric_validator], verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchatuserslist',
            unique_together={('group_ref', 'email')},
        ),
    ]
