# Generated by Django 5.0.6 on 2024-11-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0044_alter_communitychat_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='JobsHistory',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rattings',
        ),
        migrations.RemoveField(
            model_name='account',
            name='requestedJobs',
        ),
        migrations.AlterField(
            model_name='account',
            name='ProfileCoverPhoto',
            field=models.ImageField(blank=True, default='/images/fallback.jpeg', upload_to='images/', verbose_name='Profile Cover photo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='/images/fallback.jpeg', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
