# Generated by Django 5.0.6 on 2024-11-20 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0045_remove_account_jobshistory_remove_account_rattings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followdAt', models.CharField(blank=True, max_length=30, null=True)),
                ('is_mutual', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='pending', max_length=30, null=True)),
                ('followed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower_id', 'followed_id')},
            },
        ),
    ]
