# Generated by Django 5.0.6 on 2024-11-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0046_accountfollowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountfollowers',
            old_name='followdAt',
            new_name='followedAt',
        ),
    ]
