# Generated by Django 5.0.6 on 2024-11-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0047_rename_followdat_accountfollowers_followedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountfollowers',
            name='status',
        ),
    ]
