# Generated by Django 5.0.6 on 2024-11-28 08:26

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0048_remove_accountfollowers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPageCarousels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, validators=[Chat.models.alphanumeric_validator])),
                ('info', models.CharField(max_length=1024)),
                ('img', models.ImageField(blank=True, default='/AI.webp', upload_to='ai/carousels/', verbose_name='Image')),
            ],
        ),
    ]
