# Generated by Django 5.0.6 on 2024-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0050_alter_account_id_alter_accountfollowers_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchats',
            name='encryptionKey',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
