# Generated by Django 5.0.6 on 2024-12-06 12:21

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0051_personalchats_encryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchats',
            name='encryptionKey',
            field=models.CharField(default=Chat.models.generate_e2e_id, max_length=5000, unique=True, validators=[Chat.models.alphanumeric_validator], verbose_name='End to End encryption key'),
        ),
    ]
